project:
  type: website
  output-dir: docs

website:
  title: "Why zoologists shouldnâ€™t treat the ATA as an afterthought"
  navbar:
    left:
      - href: lit_analysis.qmd
        text: Literature analysis

    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/tomkeaney/inbreeding_plants_animals
format:
  html:
      theme: yeti # browse these here: https://quarto.org/docs/output-formats/html-themes.html
      max-width: 1800px # adjust if your plots don't fit or you want more or less whitespace
      toc: true # do you want a table of contents, by default it floats as you scroll
      toc-location: left # where should it be displayed
      toc-title: "Sections" 
      code-fold: true # fold code up for neater display
      smooth-scroll: true 
      embed-resources: true # output doc contains all info needed to display html
      #fig-format: svg
      grid: 
        body-width: 1000px
  